apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nikymn/dumbmerch-be
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service-backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend
  # namespace: mvp
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod-office"
spec:
  # tls:
  #   - hosts:
  #     - change.me
  #     secretName: letsencrypt
  rules:
    - host: api.nafis.studentdumbways.my.id
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-backend
              port:
                number: 5000